set nocompatible
set softtabstop=2

set incsearch
set hlsearch
set t_Co=256
" colorscheme catppuccin
set termguicolors

set wildmenu
syntax on
set lazyredraw
set showmatch

set showcmd
set laststatus=2

set breakindent
set scrolloff=10

set conceallevel=1
set showmode

nnoremap <Esc> <cmd>nohlsearch<CR>

set foldenable
set foldmethod=indent
set foldlevelstart=10
set foldnestmax=10

" change cursor depending mode
" set guicursor=n-v-c:block,i-ci:ver25,r-cr:hor20,o:hor50
:let &t_SI = "\<Esc>[6 q"
:let &t_EI = "\<Esc>[2 q"
:let &t_SR = "\<Esc>[4 q"

cabbrev <expr> W getcmdtype() == ':' && getcmdline() ==# 'W' ? 'w' : 'W'
cabbrev <expr> Wq getcmdtype() == ':' && getcmdline() ==# 'Wq' ? 'wq' : 'Wq'
cabbrev <expr> Wqa getcmdtype() == ':' && getcmdline() ==# 'Wqa' ? 'wqa' : 'Wqa'
cabbrev <expr> WQ getcmdtype() == ':' && getcmdline() ==# 'WQ' ? 'wq' : 'WQ'
cabbrev <expr> WQa getcmdtype() == ':' && getcmdline() ==# 'WQa' ? 'wqa' : 'WQa'
cabbrev <expr> WQA getcmdtype() == ':' && getcmdline() ==# 'WQA' ? 'wqa' : 'WQA'

cabbrev <expr> Q getcmdtype() == ':' && getcmdline() ==# 'Q' ? 'q' : 'Q'
cabbrev <expr> Qa getcmdtype() == ':' && getcmdline() ==# 'Qa' ? 'qa' : 'Qa'
cabbrev <expr> QA getcmdtype() == ':' && getcmdline() ==# 'QA' ? 'qa' : 'QA'

let mapleader = " " 

" NERDTree

" \ = focus NERDTree, or toggle it closed if already focused
nnoremap <silent> \ :NERDTreeFocus<CR>

" Inside NERDTree, \ closes it
autocmd FileType nerdtree nnoremap <buffer> <silent> \ :NERDTreeToggle<CR>

" Close Vim if NERDTree is the only remaining window
autocmd BufEnter * 
    \ if winnr('$') == 1 &&
    \ exists('b:NERDTree') &&
    \ b:NERDTree.isTabTree() |
    \ quit |
    \ endif

" Nerd Tree options
" let NERDTreeShowHidden = 1
let NERDTreeWinSize = 30
let NERDTreeWinPos = "left"
let NERDTreeMapToggleHidden = 'H'


